# This workflow builds your AntiSpoof Maven project and publishes it to GitHub packages when a release is created
name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Publish to GitHub Packages
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
        
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: AntiSpoof
        path: target/antispoof-*.jar
